### ISSUE TITLE
Create better icons

### ISSUE THREAD

**Issue by uncompiled** [uncompiled/alexa-fruit-stand#1]
The current icon is just a bunch of random fruit emoji, which is okay, but it would be great to have a cool icon when you look for this skill in the Alexa app.

**Comment by daviditsygin** [comment]
I can do this. Any requests for what it should look like?

**Comment by daviditsygin** [comment]
I added some new icons in #4 - let me know what you think and if I should change anything

**Comment by uncompiled** [comment]
Thanks for helping out!  Inside the Alexa app, the icon ends up being a circle, so I think a round icon with a flat design would be really great.

Here are a few icons for reference:
https://thenounproject.com/search/?q=fruit&i=137307
https://thenounproject.com/search/?q=vegetables&i=544446
https://thenounproject.com/search/?q=fruit&i=114217

Could you use one of these icons as a starting point for the design and add a splash of color to it?

**Comment by daviditsygin** [comment]
Alright, will do 👍

**Comment by uncompiled** [comment]
Merged for next release 👍
