### ISSUE TITLE
Update `xo` dependency to the latest version

### ISSUE THREAD

**Issue by uncompiled** [uncompiled/alexa-fruit-stand#34]
The `xo` dependency is really out of date.  We should update to the [latest version](https://www.npmjs.com/package/xo), which is version `0.25.3` as of writing this issue.

What you'll need to do is:
- bump the xo version in `package.json` to `0.25.3`
- run `npm test`
- Fix any linting errors reported

> NOTE: this issue is reserved for beginning developers, so please request to be assigned this issue before submitting a PR.

**Comment by aliidrees** [comment]
@uncompiled can you assign this ticket to me so that I can start looking into it?

**Comment by aliidrees** [comment]
@uncompiled PR is ready to be reviewed

https://github.com/uncompiled/alexa-fruit-stand/pull/39
