### ISSUE TITLE
Add CodeClimate badge to README

### ISSUE THREAD

**Issue by uncompiled** [uncompiled/alexa-fruit-stand#35]
[CodeClimate](https://codeclimate.com/github/uncompiled/alexa-fruit-stand/) is a neat little tool that does automated code reviews.  It does static code analysis, so it's kind of like a Cloud-based linter that gives you some insight into your project.  Although the tests run `xo` locally, it would be nice to have a CodeClimate badge on the repo showing that we care about code quality.

Instructions
- Modify the `README.md` file to contain a link to the badge.
  - The required Markdown is attached in this issue.
  - You can copy and paste this into the `README.md` file.
  - Place the badge right after the Travis CI badge
- Commit your changes and submit a PR.

Markdown for the badge
```
[![Maintainability](https://api.codeclimate.com/v1/badges/bb990d4c39537fce2ce4/maintainability)](https://codeclimate.com/github/uncompiled/alexa-fruit-stand/maintainability)
```

> NOTE: this issue is reserved for beginning developers, so please request to be assigned this issue before submitting a PR.

**Comment by basiliskav** [comment]
Please assign this to me
