### ISSUE TITLE
Add CODEOWNERS file

### ISSUE THREAD

**Issue by uncompiled** [uncompiled/alexa-fruit-stand#36]
[GitHub will automatically assign PRs](https://help.github.com/en/articles/about-code-owners) to me for review if a `CODEOWNERS` file exists in the root of the code repository.

Instructions:
- Create a file named `CODEOWNERS` in the root of the directory.
- The contents of the file should be my GitHub username: `@uncompiled`
- Commit this file, push your changes, and submit a PR.

> NOTE: this issue is reserved for beginning developers, so please request to be assigned this issue before submitting a PR.

**Comment by mbain108** [comment]
Please assign this to me.
